table Glossary
	lineageTag: 8c906f2f-e669-4509-b615-d852f0e5e483

	column 'Terms Group'
		dataType: string
		lineageTag: 7bb878c3-f820-44a7-916c-b581e3da74e3
		summarizeBy: none
		sourceColumn: Terms Group

		annotation SummarizationSetBy = Automatic

	column Terms
		dataType: string
		lineageTag: a8030380-f910-43a8-972e-5d98022511e9
		summarizeBy: none
		sourceColumn: Terms

		annotation SummarizationSetBy = Automatic

	column 'Terms Description'
		dataType: string
		lineageTag: 640a9a45-31c9-40ea-bc96-31766afd8339
		summarizeBy: none
		sourceColumn: Terms Description

		annotation SummarizationSetBy = Automatic

	partition Glossary = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dVJNT8MwDP0rVk8gDW3AgTNicJrYtDEkNHbIUreNlCZV467s3+Ok3UfX9VTLfX5+7zmbTfQmtKy0IGUNzGyqZDSKvhXW41gcuNxzCdJWhsZ3DjVKglgQPsRYaHsI9X20HW2iKSbKKE/DU+9/hS3pVECxUx4q+siprY22Ir4oAzpRGvvoOWVYOi6W6FRqMIbKcQNs2RYZj8tMmJR/rRef4HCPpdBAKkcX+G75nQYzPMKePbv/wA6pRjTAK+HREZQYrNiCCcM0o0CYGMj6qIa4vyzx/vlxyps4MYRc+y6XKNFIn/60apFHMd4laOG6OgiDEN6MQWhSostCf1DWq5RVHpp77Khr9NquRs5P65BE8waaqPrKP7RIYTlbwdo1d1q3V+Elvi2kROegVpTZimC1+GlbA1QecIPqPHeiOrMPX7m6MplbQ5kDR4LvmpQ2b+JNVNnJlywjQ658FrpKvy/8eRKeUSfUoP23mkyeXpiuG7Ay0I6MAE3cnFO5izNy0Nt/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Terms Group" = _t, Terms = _t, #"Terms Description" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Terms Group", type text}, {"Terms", type text}, {"Terms Description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

