table 'RLS Data'
	lineageTag: b931d928-24df-463a-aa45-48b0f7f7c001

	measure '~Flag RLS Users' = CALCULATE(DISTINCTCOUNT('RLS Data'[#User Name]),'RLS Data'[~Has SPY] = "N")
		formatString: 0
		lineageTag: 3193cba8-874a-4c35-bd90-aeec17eadd82

	measure '~Flag RLS Users Ratio' = DIVIDE([~Flag RLS Users], COUNT('RLS Data'[#User Name]))
		lineageTag: a053de73-7efe-42e6-b9f0-2f8da95fb771

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DNA ID'
		dataType: int64
		formatString: 0
		lineageTag: 5ba18db0-3b74-401e-9407-1dc541482884
		summarizeBy: count
		sourceColumn: DNA ID

		annotation SummarizationSetBy = Automatic

	column 'Email Address'
		dataType: string
		lineageTag: 568dab90-697c-4b93-85e8-3ee5a83b3020
		summarizeBy: none
		sourceColumn: Email Address

		annotation SummarizationSetBy = Automatic

	column 'Login ID'
		dataType: string
		lineageTag: c3c5889d-9f80-4f58-86d4-1e3ab157f5b5
		summarizeBy: none
		sourceColumn: Login ID

		annotation SummarizationSetBy = Automatic

	column 'Global ID'
		dataType: int64
		formatString: 0
		lineageTag: 2d6e5a77-4267-433e-ba27-e756080a835d
		summarizeBy: count
		sourceColumn: Global ID

		annotation SummarizationSetBy = Automatic

	column 'DNA Type'
		dataType: string
		lineageTag: f01d6d05-3d77-4391-92e0-ca1bafe52013
		summarizeBy: none
		sourceColumn: DNA Type

		annotation SummarizationSetBy = Automatic

	column 'DNA Name'
		dataType: string
		lineageTag: 9a42a147-9d91-4d01-9963-9aff15d49965
		summarizeBy: none
		sourceColumn: DNA Name

		annotation SummarizationSetBy = Automatic

	column 'DNA Value'
		dataType: string
		lineageTag: db374c3d-488a-4df0-bf22-461b00a4e63b
		summarizeBy: none
		sourceColumn: DNA Value

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: de00c701-7221-49d7-8973-784b1cd21df1
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	column 'Entry ID'
		dataType: int64
		formatString: 0
		lineageTag: 2d5d762e-f8d4-4b24-a767-d95a4c42d686
		summarizeBy: count
		sourceColumn: Entry ID

		annotation SummarizationSetBy = Automatic

	column 'Entry Datetime'
		dataType: dateTime
		formatString: General Date
		lineageTag: a07bc4b3-02f9-4f95-9b5b-9efe731c7208
		summarizeBy: none
		sourceColumn: Entry Datetime

		variation Variation
			isDefault
			relationship: a00124f4-fee9-46ca-92cd-c67ece4e950c
			defaultHierarchy: LocalDateTable_a4009110-576d-4a31-bcba-6881339c4111.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Update ID'
		dataType: int64
		formatString: 0
		lineageTag: 7264b127-1f41-4b4b-8f7f-5daf28153fc9
		summarizeBy: count
		sourceColumn: Update ID

		annotation SummarizationSetBy = Automatic

	column 'Update Datetime'
		dataType: dateTime
		formatString: General Date
		lineageTag: 01622e25-e7d9-449c-acf1-a9153d767b54
		summarizeBy: none
		sourceColumn: Update Datetime

		variation Variation
			isDefault
			relationship: 90c06b2e-4ca4-4b75-a4af-a2bc02f7e55b
			defaultHierarchy: LocalDateTable_2dc84de9-363d-47ed-abc3-6e1b67b23ec0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column '~Has SPY' = ```
			
			IF(
			    CONTAINS(
			        'PBI Spy User Access',
			        'PBI Spy User Access'[global_employee_id],
			        'RLS Data'[Global ID]
			    ),
			    "Y", 
			    "N"
			)
			```
		lineageTag: 9a642326-a530-4bb2-9089-95facc1d0ca6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '#User Name' =
			
			VAR G_ID = LOOKUPVALUE('Employee Info'[Name],'Employee Info'[Employee Global ID],'RLS Data'[Global ID])
			VAR E_ID = LOOKUPVALUE('Employee Info'[Name],'Employee Info'[userPrincipalName],'RLS Data'[Email Address])
			RETURN
			IF(G_ID <> BLANK(), G_ID, E_ID)
		lineageTag: 8c32f5f2-efe1-4a7c-9ce1-5d61c9b31d6b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'RLS Data' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\T855137W\Downloads\Export_QGen_hyve_user_dna_SNX-HV_HV_0 (1).xlsx"), null, true),
				    #"Export Data_Sheet" = Source{[Item="Export Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Export Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DNA ID", Int64.Type}, {"Email Address", type text}, {"Login ID", type text}, {"Global ID", Int64.Type}, {"DNA Type", type text}, {"DNA Name", type text}, {"DNA Value", type text}, {"Active", type text}, {"Entry ID", Int64.Type}, {"Entry Datetime", type datetime}, {"Update ID", Int64.Type}, {"Update Datetime", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

